[package]
name = "rust-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap = "1.3"
etherparse = "0.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
redis="0.25"
